### ISSUE TITLE
[Bug]: Sort by function throws error on channel page when trying to sort one video

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3251]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to https://www.youtube.com/@onetv4548
2. Use Sort by function
3. See error

```
Error: Invalid filter
    at fw.<anonymous> (renderer.js:2:1255461)
    at Generator.next (<anonymous>)
    at renderer.js:2:1254355
    at new Promise (<anonymous>)
    at pw (renderer.js:2:1254100)
    at fw.applyFilter (renderer.js:2:1255200)
    at a.getChannelVideosLocal (renderer.js:2:1574069)
getChannelVideosLocal@renderer.js:2
```

### Expected Behavior

Dont throw the error and sort the video? Or not because it is the only one.

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/actions/runs/4327256117

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
The buttons to sort are not available on the YT site 
![image](https://user-images.githubusercontent.com/78101139/225047138-d35dfdb5-9200-46ab-bc93-ddb043f25017.png)
so this is probably why an error occurs. We should probably hide the sort buttons when there is just one video. Do you get any errors when testing with Invidious?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I dont receive this error with invidious
