### ISSUE TITLE
[Bug]: Channel `TypeError: Cannot read properties of null (reading 'content')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3305]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Navigated to https://www.youtube.com/channel/UCH5DsMZAgdx5Fkk9wwMNwCA through the sidebar and got this error. Its very random sometimes it throws this and sometimes not. Fallback is disabled

Edit: Also happens at https://www.youtube.com/channel/UClRwC5Vc8HrB6vGx6Ti-lhA

```
renderer.js:2 TypeError: Cannot read properties of null (reading 'content')
    at a.<anonymous> (renderer.js:2:1060859)
    at t._render (renderer.js:2:839053)
    at a.n (renderer.js:2:869629)
    at t.get (renderer.js:2:819696)
    at t.run (renderer.js:2:820615)
    at ui (renderer.js:2:822577)
    at Array.<anonymous> (renderer.js:2:818079)
    at Le (renderer.js:2:817479)
ke @ renderer.js:2
Ce @ renderer.js:2
Te @ renderer.js:2
t._render @ renderer.js:2
n @ renderer.js:2
t.get @ renderer.js:2
t.run @ renderer.js:2
ui @ renderer.js:2
(anonymous) @ renderer.js:2
Le @ renderer.js:2
Promise.then (async)
Ee @ renderer.js:2
Ne @ renderer.js:2
(anonymous) @ renderer.js:2
t.update @ renderer.js:2
t.notify @ renderer.js:2
set @ renderer.js:2
Ri.Mi.set @ renderer.js:2
getCommunityPostsLocal @ renderer.js:2
await in getCommunityPostsLocal (async)
getChannelLocal @ renderer.js:2
await in getChannelLocal (async)
$route @ renderer.js:2
xe @ renderer.js:2
t.run @ renderer.js:2
ui @ renderer.js:2
(anonymous) @ renderer.js:2
Le @ renderer.js:2
Promise.then (async)
Ee @ renderer.js:2
Ne @ renderer.js:2
(anonymous) @ renderer.js:2
t.update @ renderer.js:2
t.notify @ renderer.js:2
set @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
Bl.updateRoute @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
Dl @ renderer.js:2
(anonymous) @ renderer.js:2
n @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
g @ renderer.js:2
n @ renderer.js:2
n @ renderer.js:2
Dl @ renderer.js:2
Bl.confirmTransition @ renderer.js:2
Bl.transitionTo @ renderer.js:2
e.push @ renderer.js:2
(anonymous) @ renderer.js:2
Kl.push @ renderer.js:2
push @ renderer.js:2
v @ renderer.js:2
xe @ renderer.js:2
n @ renderer.js:2
Un.r._wrapper @ renderer.js:2


```

### Expected Behavior

Dont throw the error.

### Issue Labels

API issue

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/6362d65c119668d4b74135474a2a849a27e03e8e

### Operating System Version

win 10 22h2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can confirm it was present in https://github.com/FreeTubeApp/FreeTube/commit/6362d65c119668d4b74135474a2a849a27e03e8e but isnt anymore now
