### ISSUE TITLE
[Bug]: `TypeError: Cannot read properties of undefined (reading 'title')`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3386]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Noticed this error when testing https://github.com/FreeTubeApp/FreeTube/pull/3362 but i dont notice any issues with FT.

1. Play any playlist
2. Go to the end of the video
3. Let the countdown do its thing
4. Next video load
5. Error

```
TypeError: Cannot read properties of undefined (reading 'title')
    at a.currentTitle (renderer.js:2:1688331)
    at t.get (renderer.js:2:827872)
    at t.evaluate (renderer.js:2:829054)
    at a.currentTitle (renderer.js:2:841873)
    at a.<anonymous> (renderer.js:2:1689246)
    at t._render (renderer.js:2:847229)
    at a.n (renderer.js:2:877807)
    at t.get (renderer.js:2:827872)
    at t.run (renderer.js:2:828791)
    at hi (renderer.js:2:830753)
```

The following error spams the console but i think that would be resolved if the first one gets solved

```
renderer.js:2 TypeError: Cannot read properties of undefined (reading 'startSeconds')
    at a.updateCurrentChapter (renderer.js:2:1742147)
    at Ce (renderer.js:2:825205)
    at a.i (renderer.js:2:818550)
    at Ce (renderer.js:2:825205)
    at t.$emit (renderer.js:2:846105)
    at e.<anonymous> (renderer.js:2:1654674)
    at n.dispatcher.n.dispatcher (renderer.js:2:238929)
    at hn (renderer.js:2:239927)
    at e.trigger (renderer.js:2:244598)
    at wa.forEach.ka.<computed> [as handleTechTimeupdate_] (renderer.js:2:433352)
```

Watch 0-20 sec and then skip to the 1min mark (i got distracted a bit)

https://user-images.githubusercontent.com/73130443/229303197-da4bd05a-3fd4-4b0b-a198-534cd39e2591.mp4

### Expected Behavior

No error

### Issue Labels

API issue

### FreeTube Version

Latest nightly

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
It's not just any playlist, it's that specific playlist in the video.
The fifth video in the playlist "Have you ever dropped your phone into a lake?" has a chapter at 11:30 but the video is only 11:31 long, so for some reason that chapter being right at the end is causing problems for the next video.
