### ISSUE TITLE
[Bug]: Live chat `Uncaught Error: not an array of text runs`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#3583]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads)
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I was listening to https://youtu.be/jfKfPfyJRdk, opened the dev tools and saw the following error

```
Uncaught Error: not an array of text runs
    at FR (renderer.js:2:1364942)
    at a.parseLiveChatSuperChat (renderer.js:2:1644015)
    at renderer.js:2:1643196
    at RP.i (renderer.js:2:1123088)
    at RP.emit (renderer.js:2:1123018)
    at RP.<anonymous> (renderer.js:2:1125012)
    at Generator.next (<anonymous>)
    at a (renderer.js:2:871570)
```

### Expected Behavior

Hmm not sure everything seems to be working fine

### Issue Labels

content not loading

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/3e543aeb242f087951beee25d79385702c35f7cd

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Cant reproduce anymore
