### ISSUE TITLE
[Bug]: Age restricted videos get speed throttled and comments don’t load

### ISSUE THREAD

**Issue by hollownights** [FreeTubeApp/FreeTube#3738]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When trying to play age restricted videos like [this one](https://www.youtube.com/watch?v=rrSnnhe53ks), the speed is terribly throttled and the comments just won’t load. I’ve tried with 0.18.0-nightly-3089, so this problem isn’t a thing of the past. My settings are: “Preferred API backend: Local API” is set, “Revert to non-preferred backend on failure” is enabled and “Proxy Videos Through Invidious” is disabled.

I’ve also tried playing the same video on NewPipe, which also gets speed throttled, but it can load the comments. Also tried downloading with yt-dlp 2023.07.06 and it is able to download the video with no problems, no throttling at all.

### Expected Behavior

No speed throttling and comments loaded.

### Issue Labels

content not loading, inconsistent behavior

### FreeTube Version

3089

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
This is expected, as the throttling bypass we use, only helps with the android client, the web one and the one we use to bypass age restrictions are still throttled.

This will hopefully be fixed when we do the major refactor to use a different video player that behaves more similarly to the official website, As that is a lot of work (basic playback is easy, but we'll have to reimplement all of the custom features that accumulated over time, that are written for the current player) and we are planning to do the next release soon, it won't be included in or worked on before the next release.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Any idea why the comment arent loading? I can see them just fine on YT side

**Comment by hollownights** [comment]
@absidue Thanks for the answer!

@efb4f5ff-1298-471a-8973-3d47447115dc I tried looking it up a bit, but couldn't see anything too obvious (to my limited knowledge). I'm also able to load the comments in the browser. Here is the console output, anyway:

```
renderer.js:2 VIDEOJS: WARN: using Vhs.BANDWIDTH_VARIANCE is UNSAFE be sure you know what you are doing
(anonymous) @ renderer.js:2
renderer.js:2 CommentsSimplebox not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
Introspected and JIT generated this class in the meantime:
class CommentsSimplebox extends YTNode {
  static type = 'CommentsSimplebox';

  simplebox_avatar: Thumbnail[];
  simplebox_placeholder: Text;

  constructor(data: RawNode) {
    super();
    this.simplebox_avatar = Thumbnail.fromResponse(data.simpleboxAvatar);
    this.simplebox_placeholder = new Text(data.simpleboxPlaceholder);
  }
}

bI @ renderer.js:2
createRuntimeClass @ renderer.js:2
generateRuntimeClass @ renderer.js:2
parseItem @ renderer.js:2
Rg @ renderer.js:2
parseItem @ renderer.js:2
parseArray @ renderer.js:2
Fb @ renderer.js:2
parseItem @ renderer.js:2
parseArray @ renderer.js:2
LT @ renderer.js:2
parseItem @ renderer.js:2
parse @ renderer.js:2
parseResponse @ renderer.js:2
kE @ renderer.js:2
TE @ renderer.js:2
(anonymous) @ renderer.js:2
a @ renderer.js:2
Promise.then (async)
l @ renderer.js:2
(anonymous) @ renderer.js:2
Pu @ renderer.js:2
getInfo @ renderer.js:2
YR @ renderer.js:2
await in YR (async)
getVideoInformationLocal @ renderer.js:2
mounted @ renderer.js:2
Pe @ renderer.js:2
ni @ renderer.js:2
insert @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
t._update @ renderer.js:2
n @ renderer.js:2
t.get @ renderer.js:2
t.run @ renderer.js:2
fi @ renderer.js:2
(anonymous) @ renderer.js:2
Me @ renderer.js:2
Promise.then (async)
Le @ renderer.js:2
Ve @ renderer.js:2
(anonymous) @ renderer.js:2
t.update @ renderer.js:2
t.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
r @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
c @ renderer.js:2
u @ renderer.js:2
renderer.js:2 Error: Something went wrong at CommentsSimplebox!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at NI.<anonymous> (renderer.js:2:1103753)
    at NI.parseItem (renderer.js:2:1100139)
    at new Rg (renderer.js:2:989981)
    at NI.parseItem (renderer.js:2:1100046)
    at NI.parseArray (renderer.js:2:1100291)
    at new Fb (renderer.js:2:1018867)
    at NI.parseItem (renderer.js:2:1100046)
    at NI.parseArray (renderer.js:2:1100291)
    at new LT (renderer.js:2:1077931)
    at NI.parseItem (renderer.js:2:1100046)
(anonymous) @ renderer.js:2
parseItem @ renderer.js:2
Rg @ renderer.js:2
parseItem @ renderer.js:2
parseArray @ renderer.js:2
Fb @ renderer.js:2
parseItem @ renderer.js:2
parseArray @ renderer.js:2
LT @ renderer.js:2
parseItem @ renderer.js:2
parse @ renderer.js:2
parseResponse @ renderer.js:2
kE @ renderer.js:2
TE @ renderer.js:2
(anonymous) @ renderer.js:2
a @ renderer.js:2
Promise.then (async)
l @ renderer.js:2
(anonymous) @ renderer.js:2
Pu @ renderer.js:2
getInfo @ renderer.js:2
YR @ renderer.js:2
await in YR (async)
getVideoInformationLocal @ renderer.js:2
mounted @ renderer.js:2
Pe @ renderer.js:2
ni @ renderer.js:2
insert @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
t._update @ renderer.js:2
n @ renderer.js:2
t.get @ renderer.js:2
t.run @ renderer.js:2
fi @ renderer.js:2
(anonymous) @ renderer.js:2
Me @ renderer.js:2
Promise.then (async)
Le @ renderer.js:2
Ve @ renderer.js:2
(anonymous) @ renderer.js:2
t.update @ renderer.js:2
t.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
r @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
c @ renderer.js:2
u @ renderer.js:2
renderer.js:2 Error: Something went wrong at ClickTrackingParams!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at NI.<anonymous> (renderer.js:2:1103753)
    at NI.parseItem (renderer.js:2:1100139)
    at new Qv (renderer.js:2:1002880)
    at NI.parseItem (renderer.js:2:1100046)
    at NI.parseArray (renderer.js:2:1100291)
    at new ey (renderer.js:2:1003407)
    at NI.parseItem (renderer.js:2:1100046)
    at new ny (renderer.js:2:1003570)
    at NI.parseItem (renderer.js:2:1100046)
    at renderer.js:2:1099360
(anonymous) @ renderer.js:2
parseItem @ renderer.js:2
Qv @ renderer.js:2
parseItem @ renderer.js:2
parseArray @ renderer.js:2
ey @ renderer.js:2
parseItem @ renderer.js:2
ny @ renderer.js:2
parseItem @ renderer.js:2
(anonymous) @ renderer.js:2
parseResponse @ renderer.js:2
kE @ renderer.js:2
TE @ renderer.js:2
(anonymous) @ renderer.js:2
a @ renderer.js:2
Promise.then (async)
l @ renderer.js:2
(anonymous) @ renderer.js:2
Pu @ renderer.js:2
getInfo @ renderer.js:2
YR @ renderer.js:2
await in YR (async)
getVideoInformationLocal @ renderer.js:2
mounted @ renderer.js:2
Pe @ renderer.js:2
ni @ renderer.js:2
insert @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
t._update @ renderer.js:2
n @ renderer.js:2
t.get @ renderer.js:2
t.run @ renderer.js:2
fi @ renderer.js:2
(anonymous) @ renderer.js:2
Me @ renderer.js:2
Promise.then (async)
Le @ renderer.js:2
Ve @ renderer.js:2
(anonymous) @ renderer.js:2
t.update @ renderer.js:2
t.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
r @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
c @ renderer.js:2
u @ renderer.js:2
renderer.js:2 Failed to fetch android formats {"status":"LOGIN_REQUIRED","reason":"This video may be inappropriate for some users.","embeddable":false,"audio_only_playablility":null,"error_screen":{"type":"ConfirmDialog","title":{"runs":[{"text":"You must sign in to view this video","bold":false,"italics":false,"strikethrough":false}],"text":"You must sign in to view this video"},"confirm_button":{"type":"Button","text":"Sign in","is_disabled":false,"endpoint":{"type":"NavigationEndpoint","payload":{},"metadata":{}}},"cancel_button":{"type":"Button","text":"Go back","is_disabled":false,"endpoint":{"type":"NavigationEndpoint","payload":{},"metadata":{}}},"dialog_messages":[{"runs":[{"text":"This video may be inappropriate for some users.","bold":false,"italics":false,"strikethrough":false}],"text":"This video may be inappropriate for some users."}]}}
YR @ renderer.js:2
await in YR (async)
getVideoInformationLocal @ renderer.js:2
mounted @ renderer.js:2
Pe @ renderer.js:2
ni @ renderer.js:2
insert @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
T @ renderer.js:2
(anonymous) @ renderer.js:2
t._update @ renderer.js:2
n @ renderer.js:2
t.get @ renderer.js:2
t.run @ renderer.js:2
fi @ renderer.js:2
(anonymous) @ renderer.js:2
Me @ renderer.js:2
Promise.then (async)
Le @ renderer.js:2
Ve @ renderer.js:2
(anonymous) @ renderer.js:2
t.update @ renderer.js:2
t.$forceUpdate @ renderer.js:2
(anonymous) @ renderer.js:2
r @ renderer.js:2
Pe @ renderer.js:2
i @ renderer.js:2
(anonymous) @ renderer.js:2
(anonymous) @ renderer.js:2
c @ renderer.js:2
u @ renderer.js:2
```
