### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BugreportFreetube** [FreeTubeApp/FreeTube#3952]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Video wont start if you try to play one. Does not matter where you found that video in the app.
Instead it starts to blink infinitely with following Error message:

play() request Error (Click to copy): NotSupportedError: Failed to load because no supported source was found.

This Error message will appear also multiple times infinitely row under row under row.
Bug appeared since v0.19.0 Beta (Flatpak)
Freetube just won´t play any videos from now on. 

There is a weird exception though. Occasionally when I start a video which is NOT listed in any feed or playlist and I haven’t watched it yet (Found the video by typing first a word in the search bar and choosing then a video to play), then it MIGHT will work as expected. From now on every video will play as expected, as long as the Freetube app is open.
If I close the program and reopen it, the same issues are remaining. 

Hard to reproduce this temporary bug fix, as I mentioned, it happens occasionally, like 1 out of 20 or so.
For me it worked 2 times.

### Expected Behavior

Simply playing the video.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.19.0 Beta  (Flatpak)

### Operating System Version

POP OS  22.04 LTS

### Installation Method

other

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

any other versions before.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
Do you have "Proxy Videos Through Invidious" in the "Player Settings" enabled?

**Comment by Anonymous1157** [comment]
I have the same problem on 0.19.0 from the Github Releases. FreeTube local API cannot play any videos and the video player will blink the thumbnail.

A workaround is to use the Invidious API, but you have to check the list of instances and manually set FreeTube to use one that's on the latest version, or the Invidious API will also have the same problem.

Proxying the videos through Invidious doesn't work with either API, same problem.

**Comment by absidue** [comment]
Proxying through Invidious not working is because YouTube is blocking video proxying on Invidious servers, see #3892 for more.

The question is do you get play errors while proxying is disabled?

**Comment by absidue** [comment]
We need to know if this is its own issue or a duplicate of the other one.

**Comment by Anonymous1157** [comment]
Yes, I am still unable to play videos with video proxying disabled as well.

**Comment by absidue** [comment]
What have you set the default format to (DASH, audio or legacy)? and do any of the others work?

**Comment by absidue** [comment]
@Anonymous1157 Do you have the Allow AV1 setting enabled?

**Comment by joncomas** [comment]
Hi, I had the same issue from 0.18.0 to 0.19.0, I cloned the repo today to try to fix it and contribute some code but then I realized the Electron build from VsCode works perfectly. 

So I uninstalled the app from my Applications folder and - most importantly - deleted the "FreeTube" folder from my application Support's folder (I'm on Mac) then reinstalled and it worked. 

The issue is solved for me. Can somebody here try

PS: Don't forget to export your data (Subscriptions, history etc) before trying this, so you can Import it later.

**Comment by Anonymous1157** [comment]
@absidue I figured out that the blinking thumbnail was caused by turning on "Fallback to Non-Preferred Backend on Failure" when the Invidious instance I was using was also not working so it was rapidly switching back and forth instead of just telling me both failed. If I have a working Invidious instance set and this option turned on then the local API still fails but fallback to Invidious API works and it does not blink.

I now get a blank video page with blank player and empty boxes where description and suggested videos would go and "TypeError: Cannot read properties of undefined (reading 'replace')".

None of DASH, audio, legacy, or AV1 work, same behavior. Sometimes I get a black video player with the big play button in the middle as if it's going to load the thumbnail, but it does not load and I cannot play the video.

**Comment by absidue** [comment]
Can you try opening the dev tools (CTRL+SHIFT+I or CMD+SHIFT+I on macOS), switching to the network tab and then going to a video page on the local API. Are any of the requests red? What numbers does it say in the status column?

**Comment by absidue** [comment]
@joncomas glad you were able to fix the issue on your side.

**Comment by Anonymous1157** [comment]
@absidue All of the requests in the Network tab of the inspector when clicking on a video with the local API were status 200. There are a lot less requests being made than with the Invidious API.

There are errors in the Console that might be useful:
```
renderer.js:2 TypeError: Cannot read properties of undefined (reading 'replace')
    at LM.<anonymous> (renderer.js:2:1351143)
    at Generator.next (<anonymous>)
    at renderer.js:2:875303
    at new Promise (<anonymous>)
    at Au (renderer.js:2:875048)
    at LM.PM (renderer.js:2:1350839)
    at LM.<anonymous> (renderer.js:2:1349577)
    at Generator.next (<anonymous>)
    at renderer.js:2:875303
    at new Promise (<anonymous>)
getVideoInformationLocal	@	renderer.js:2

renderer.js:2 TypeError: Cannot read properties of undefined (reading 'bitrate')
    at a.determineDefaultQualityDash (renderer.js:2:1652705)
    at a.mounted (renderer.js:2:1640567)
    at Ee (renderer.js:2:670175)
    at si (renderer.js:2:675208)
    at Object.insert (renderer.js:2:678625)
    at T (renderer.js:2:714421)
    at a.__patch__ (renderer.js:2:715779)
    at t._update (renderer.js:2:691070)
    at a.n (renderer.js:2:722641)
    at t.get (renderer.js:2:672829)
```

**Comment by BugreportFreetube** [comment]
> Do you have "Proxy Videos Through Invidious" in the "Player Settings" enabled?

Yes, indeed. Sry, it seems like for me the issue is a duplicate of the other one.

"because YouTube is blocking video proxying on Invidious servers"
But why all of the sudden this bug emerged immediately in the newest build of Freetube then?
1 minute before I updated it to the newer version I could proxy them just fine with the old version.

**Comment by absidue** [comment]
@BugreportFreetube Were you using the legacy formats? Previously they weren't getting properly proxied through Invidious, now they are. If not, it's probably just a coincidence, YouTube does their Invidious and Piped IP bans in waves, so it might have coincided with you upgrading to 0.19.0.

**Comment by absidue** [comment]
@Anonymous1157 Thanks for the errors, I'll try digging in the code later to see if I can find the source of them. Did they both occur on the local API or the Invidious API (I suspect the first is local, the second Invidious)? Also what video did this happen on and if you are using Invidious could please provide the URL of the instance?

I'm not getting this on any videos I've tried but I definitely want to figure out why it's happening and try to fix it.

**Comment by Anonymous1157** [comment]
Both of them are coming from the local API. The Invidious API works perfectly with no Console errors.

The local API works as expected on my Windows 10 machine with 0.19.0 from winget (I believe this just installs the Github Release).

I got slightly different Console errors running HEAD from Git in dev mode:
```
Watch.js?5b49:696 TypeError: Cannot read properties of undefined (reading 'replace')
    at Session.eval (Session.js?da8e:152:1)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js?9ab4:121:1)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?9ab4:117:1)
    at Session._Session_retrieveSessionData (Session.js?da8e:139:1)
    at Session.eval (Session.js?da8e:63:1)
    at Generator.next (<anonymous>)
    at eval (tslib.es6.js?9ab4:121:1)
    at new Promise (<anonymous>)

vue.runtime.esm.js?2b0e:4605 [Vue warn]: Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'bitrate')"

found in

---> <FtVideoPlayer> at src/renderer/components/ft-video-player/ft-video-player.vue
       <Watch> at src/renderer/views/Watch/Watch.vue
         <FtFlexBox> at src/renderer/components/ft-flex-box/ft-flex-box.vue
           <App> at src/renderer/App.vue
             <Root>

vue.runtime.esm.js?2b0e:3049 TypeError: Cannot read properties of undefined (reading 'bitrate')
    at VueComponent.determineDefaultQualityDash (ft-video-player.js?63bd:1118:1)
    at VueComponent.mounted (ft-video-player.js?63bd:390:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:3017:1)
    at callHook$1 (vue.runtime.esm.js?2b0e:4031:1)
    at Object.insert (vue.runtime.esm.js?2b0e:4423:1)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6942:1)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:7153:1)
    at Vue._update (vue.runtime.esm.js?2b0e:3769:1)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:3868:1)
    at Watcher.get (vue.runtime.esm.js?2b0e:3446:1)
```

I discovered I cannot even load the Trending page (which I don't normally use) via the local API. I get the same "replace" error but on "Trending.js?2db6:113".

**Comment by Anonymous1157** [comment]
@absidue  I ran a git bisect and commit bcf21f6d446d5aa60429b14b28aa14110c7f3b12 is the one that breaks local API for me.

**Comment by absidue** [comment]
@Anonymous1157 I don't know why but for some reason the session generation seems to be failing for you, but nobody else.
This [YouTube.js pull request](https://github.com/LuanRT/YouTube.js/pull/490) adds a fallback for the remote session generation, which we only use on the watch page. But considering that the local generation is failing for you as well and that generates the session in javascript, without making any requests, it sounds like it will still be broken for you.

Would be useful if you could do some debugging as to why it's failing for you, as I can't replicate the issue on my side and it would be good if we don't have to rely on a fallback (generating a real session on the watch page, should hopefully avoid playback issues, as it we will appear closer to the behaviour of the real YouTube watch page).
You mentioned that the request to `https://www.youtube.com/sw.js_data` was succeeding right (made on the watch page to get the data to generate a session from)?
