### ISSUE TITLE
[Feature Request]: Shortcut key for "Toggle Loop" 

### ISSUE THREAD

**Issue by shadycloud** [FreeTubeApp/FreeTube#4298]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

 Much like, [Feature Request]: Keyboard shortcut to toggle autoplay #4103, 
At this moment a shortcut for the Toggle Loop button is not part of the media player. 

### Proposed Solution

A keyboard shortcut for the "Toggle Loop" video player button  "R" or "r"    (mnemonic for replay)

"L" or "l" for "Loop" wont work since it's already used... 
https://docs.freetubeapp.io/usage/keyboard-shortcuts/

### Alternatives Considered

NA

### Issue Labels

display more information to user, ease of use improvement, improvement to existing feature, new keyboard shortcut, visual improvement

**Comment by shadycloud** [comment]
@Hector118, @fdarcey, @ubello64, @Ksterner2, and I got this feature working yesterday on a machine but it was with version 0.19.0... Was going to put in a pull request this morning so we can be closer to having a shortcut for every player button, in turn closing #1587 However, `Toggle Loop` seems to be in a state of flux using fresh clone w/ Ubuntu 22.04, because I get the following error message. Was going to make a bug report, but the Toggle Loop feature is working on the latest github release I just tested.
```
case 'R':
case 'r':
  event.preventDefault()
  this.toggleVideoLoop()
  break
```
![Screenshot from 2023-11-10 09-57-12](https://github.com/FreeTubeApp/FreeTube/assets/13189052/92df09ce-0d4a-498e-bd81-eb261cf79811)

``` 
video.es.js:229 VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'value')
    at VueComponent.toggleVideoLoop (ft-video-player.js:1450:1)
    at loopButton.handleClick (ft-video-player.js:1424:1)
    at ClickableComponent._this.handleClick_ (video.es.js:10585:1)
    at data.dispatcher (video.es.js:2312:1) ```

**Comment by shadycloud** [comment]
Closing for same reason as https://github.com/FreeTubeApp/FreeTube/pull/4227#issuecomment-1817706760
