### ISSUE TITLE
0.7.2 Mac Video unavailable

### ISSUE THREAD

**Issue by big610** [FreeTubeApp/FreeTube#440]
Hello Preston,
0.7.2 Mac Video unavailable. Read your change explanation log ytdl-core. I'm late catching this version, 3rd party software's did not detect you changed the code again until 12/26. Let me know what it is going to be and I will pass it along. Also remember to zip the .dmg & .exe that keeps the original date & time of the .dmg/.exe; versus not zipped becomes the date & time of download. This way we can see immediately your release date. 0.7.1 is intermittent, pink bouncing ball video not loading, back & forth on loading or not loading. Fully understand working full time. Thanks again.
Look at these two open source apps to get an idea how they avoid problems, give you a shortcut since your time is consumed. 
SopoTube https://soponext.com/ Mac Released 05/24/19
MediaTube https://www.mediahuman.com/mediatube/ Windows & Mac Released 12/23/19

**Comment by rm-rf-home** [comment]
For me too, 0.7.2 Mac video unavailable for all videos, since weeks/months. Btw thanks for the great app otherwise!

> general.js:41 [8/3/2020@13:40:49] [FREETUBE] [Error: This video is unavailable
    at /Applications/FreeTube.app/Contents/Resources/app.asar/node…]0: Error: This video is unavailable
    at /Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/ytdl-core/lib/info.js:255:16
    at /Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/ytdl-core/lib/info.js:373:9
    at /Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/ytdl-core/lib/info.js:198:5
    at PassThrough.<anonymous> (/Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/miniget/lib/index.js:205:30)
    at PassThrough.emit (events.js:200:13)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)message: "This video is unavailable"stack: "Error: This video is unavailable↵    at /Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/ytdl-core/lib/info.js:255:16↵    at /Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/ytdl-core/lib/info.js:373:9↵    at /Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/ytdl-core/lib/info.js:198:5↵    at PassThrough.<anonymous> (/Applications/FreeTube.app/Contents/Resources/app.asar/node_modules/miniget/lib/index.js:205:30)↵    at PassThrough.emit (events.js:200:13)↵    at endReadableNT (_stream_readable.js:1154:12)↵    at processTicksAndRejections (internal/process/task_queues.js:84:9)"__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: Objectlength: 1__proto__: Array(0)concat: ƒ concat()arguments: (...)caller: (...)length: 1name: "concat"__proto__: ƒ ()[[Scopes]]: Scopes[0]constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object
