### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token (1:47)

### ISSUE THREAD

**Issue by Growebis** [FreeTubeApp/FreeTube#5378]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Right now, any video i've tried to open always throws at me SyntaxError: Unexpected token (1:47) and then it falls back to invidious.

Steps to reproduce:
1. Go to a video.
2. Get instantly hit with the error, which causes FreeTube to fall back to Invidious.

Examples of videos being affected by this error:
https://youtu.be/Y_jI_Toq0rI
https://youtu.be/1wG1NiqOqPw
https://youtu.be/bcyu7RuXqMQ

### Expected Behavior

For the video to play normally without error.

### Issue Labels

content not loading

### FreeTube Version

v0.21.0-nightly-4555 Beta

### Operating System Version

Linux Mint 21.3 Cinnamon X.org

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

Video demonstration:
https://github.com/FreeTubeApp/FreeTube/assets/113867283/a9f926bb-fa0a-46b1-9996-2aabdf61954b

Shorts and live streams are affected too.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by John-foobar-Doe** [comment]
I have encountered exactly the same issue, since about 1 or 2 hours ago. I'm not sure if YouTube changes something...

**Comment by weltivambian** [comment]
Getting the same error. The video page will then look like this:

![image](https://github.com/FreeTubeApp/FreeTube/assets/157758610/63f8fc69-0d55-44e8-81c0-9ad20492e451)

This seems to happen to *every* video I try.

**Comment by Growebis** [comment]
> I have encountered exactly the same issue, since about 1 or 2 hours ago. I'm not sure if YouTube changes something...

based on the fact that NewPipe, Invidious and yt-dlp are partially broken right now because of changes made by YouTube means Youtube must have implemented something drastic for FreeTube to be completely broken (at least for me).

**Comment by rjdg14** [comment]
> > I have encountered exactly the same issue, since about 1 or 2 hours ago. I'm not sure if YouTube changes something...
> 
> based on the fact that NewPipe, Invidious and yt-dlp are partially broken right now because of changes made by YouTube means Youtube must have implemented something drastic for FreeTube to be completely broken (at least for me).

All videos on NewPipe suddenly seem to be broken as well. This suggests some kind of major change at YouTube's end.

**Comment by PerpetualNooby** [comment]
Identical error 5 mins ago.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please refrain from commenting as we are already working on a fix. Please just upvote the issue. 

[Upstream draft fix](https://github.com/LuanRT/YouTube.js/pull/682)

**Comment by p-4-o-l-o** [comment]
Just to confirm I have exact same problem and error code:

SyntaxError: Unexpected token (1:47)

I've tried different backends, toggling fallback option, and by doing that the local option will retrieve channel logos, but the video still won't play. 

UK location.

**Comment by thingsiplay** [comment]
> Set the Invidious API as your primary API as a temporarily workaround.

Invidious API isn't working for me either.

**Comment by PerpetualNooby** [comment]
This fix didn't work for me, please reply if I did not get the settings right.

Invidious API Error (Click to copy): undefined

Invidious API Error (Click to copy): undefined

Invidious API Error (Click to copy): undefined

Invidious API Error (Click to copy): undefined

[image.png]

A
SubscriptionsChannelsPlaylistsHistory
---------------------------------------------------------------
SettingsAbout
---------------------------------------------------------------

[image.png]Subscriptions

VIDEOS
SHORTS
LIVE
COMMUNITY

**Comment by thingsiplay** [comment]
> This fix didn't work for me, please reply if I did not get the settings right.
> Invidious API Error (Click to copy): undefined Invidious API Error (Click to copy): 

I had the same error. The Invidious instance you are using does not work, but others do. Change the Invidious instance at "Current Invidious Instance" field and make it to default by clicking "Set Current Instance as Default".

**Comment by PerpetualNooby** [comment]
👍 Thanks, that worked!

**Comment by rjdg14** [comment]
The Invidious instance I used earlier worked fine, and I think the software has found a workaround for at least YouTube's previous new restriction a few weeks back. Hopefully the problem will be resolved in the next few days.

**Comment by rjdg14** [comment]
The Android app NewPipe gives a more detailed log than FreeTube of what may be going on:

`## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=CanCZktm0TQ
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Nokia/ScarletWitch_00EEA/SCW_sprout:13/TKQ1.220807.001/00WW_3_400:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)`

**Comment by PikachuEXE** [comment]
Fix in https://github.com/FreeTubeApp/FreeTube/pull/5384

**Comment by senolfndk** [comment]
api error

https://github.com/FreeTubeApp/FreeTube/assets/52818836/2d1faf10-faf8-4331-9974-bb5505ad2454

**Comment by qupear** [comment]
> Fix in #5384

Now we wait until this action end up with build, correct? Latest build related to #5380 and it still have this api issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We will do a hotfix release (v0.21.1) when that tested and merged.

**Comment by RoryTate** [comment]
Using build #4558 but issue still seems to be happening.

https://github.com/FreeTubeApp/FreeTube/assets/7506514/4137082f-854d-4780-aeed-a5cfa7a3e8d9

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Fix has been merged. We aim to put out the hotfix release ASAP!

**Comment by davresmor** [comment]
> Fix has been merged. We aim to put out the hotfix release ASAP!

where will the hotfix be available?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I will provide that information once the hotfix is available.

**Comment by ACR-Jeff** [comment]
Tested freetube-0.21.0-nightly-4559 and it's working for me

**Comment by scoop96** [comment]
> Tested freetube-0.21.0-nightly-4559 and it's working for me, Which is in the latest nightly.

where can i download? i dont find it

**Comment by ACR-Jeff** [comment]
> > Tested freetube-0.21.0-nightly-4559 and it's working for me, Which is in the latest nightly.
> 
> where can i download? i dont find it

https://github.com/FreeTubeApp/FreeTube?tab=readme-ov-file#automated-builds-nightly--weekly

**Comment by UnconsciousBlaringHuman** [comment]
> > Tested freetube-0.21.0-nightly-4559 and it's working for me, Which is in the latest nightly.
> 
> where can i download? i dont find it

"[Actions](https://github.com/FreeTubeApp/FreeTube/actions)" tab in this repo, then, on the sidebar, go to "[Build](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml)" and download the most recent one (as of the time of this comment, that would be [nightly 4560](https://github.com/FreeTubeApp/FreeTube/actions/runs/9882378042)).

**Comment by ACR-Jeff** [comment]
> > > Tested freetube-0.21.0-nightly-4559 and it's working for me, Which is in the latest nightly.
> > 
> > 
> > where can i download? i dont find it
> 
> "[Actions](https://github.com/FreeTubeApp/FreeTube/actions)" tab in this repo, then, on the sidebar, go to "[Build](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml)" and download the most recent one (as of the time of this comment, that would be [nightly 4560](https://github.com/FreeTubeApp/FreeTube/actions/runs/9882378042)).

Yes correct if going to the actions page, The link I posted before has a direct link to build, Can click the latest with a green checkmark, Follow on down the page to your preferred download.

**Comment by edesserdt** [comment]
> > > > Tested freetube-0.21.0-nightly-4559 and it's working for me, Which is in the latest nightly.
> > > 
> > > 
> > > where can i download? i dont find it
> > 
> > 
> > "[Actions](https://github.com/FreeTubeApp/FreeTube/actions)" tab in this repo, then, on the sidebar, go to "[Build](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml)" and download the most recent one (as of the time of this comment, that would be [nightly 4560](https://github.com/FreeTubeApp/FreeTube/actions/runs/9882378042)).
> 
> Yes correct if going to the actions page, The link I posted above I did for the reason the user should read the warnings, Etc, The link also has a direct link to build, Can click the latest with a green checkmark, Follow on down the page to your preferred download.

I still do not see where to "download it"

**Comment by rugabunda** [comment]
> I still do not see where to "download it"
https://github.com/FreeTubeApp/FreeTube/actions/runs/9882378042

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
v0.21.1 has been released! You can download the latest version using the following methods:
- [Our release page](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.21.1-beta)
- [Through our website](https://freetubeapp.io/#download)

**Comment by PerpetualNooby** [comment]
Thank you!!! Works great.
