### ISSUE TITLE
[Bug]: Video page won't load due to Local API Error "Unexpected token (1:47)"

### ISSUE THREAD

**Issue by UnconsciousBlaringHuman** [FreeTubeApp/FreeTube#5379]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When opening _any_ video, the following error occurs:

`Local API Error: SyntaxError: Unexpected token (1:47)`

Full console log (I've made it more readable if it helps):
```
renderer.js:2 	VIDEOJS: WARN: using Vhs.BANDWIDTH_VARIANCE is UNSAFE be sure you know what you are doing
				(anonymous)	@ renderer.js:2
				a.warn		@ renderer.js:2
				get		@ renderer.js:2
				(anonymous)	@ renderer.js:2
				(anonymous)	@ renderer.js:2
				(anonymous)	@ renderer.js:2
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
	www.youtube.com/sw.js_data:1	Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		sw.js_data:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		sw.js_data:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		iframe_api:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		iframe_api:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		iframe_api:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		player:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		player:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		player:1		Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		next:1			Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		next:1			Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
		next:1			Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
renderer.js:2 	SyntaxError: Unexpected token (1:47) (at renderer.js:2:1322561)
			at mL.raise (renderer.js:2:1322561)
			at XA.unexpected (renderer.js:2:1267963)
			at XA.semicolon (renderer.js:2:1267686)
			at tL.parseVarStatement (renderer.js:2:1276943)
			at tL.parseStatement (renderer.js:2:1271307)
			at tL.parseBlock (renderer.js:2:1278371)
			at hL.parseFunctionBody (renderer.js:2:1319341)
			at tL.parseFunction (renderer.js:2:1281089)
			at tL.parseFunctionStatement (renderer.js:2:1274572)
			at tL.parseStatement (renderer.js:2:1270878)
		getVideoInformationLocal			@ renderer.js:2
		await in getVideoInformationLocal (async)
		onMountedDependOnLocalStateLoading		@ renderer.js:2
		mounted						@ renderer.js:2
		Si						@ renderer.js:2
		gn						@ renderer.js:2
		insert						@ renderer.js:2
		x						@ renderer.js:2
		Qa.nodeOps					@ renderer.js:2
		t._update					@ renderer.js:2
		n						@ renderer.js:2
		t.get						@ renderer.js:2
		t.run						@ renderer.js:2
		Pn						@ renderer.js:2
		(anonymous)					@ renderer.js:2
		Ei						@ renderer.js:2
		Promise.then (async)    
		Ti						@ renderer.js:2
		Ri						@ renderer.js:2
		In						@ renderer.js:2
		t.update					@ renderer.js:2
		t.notify					@ renderer.js:2
		set						@ renderer.js:2
		Zn.Jn.set					@ renderer.js:2
		(anonymous)					@ renderer.js:2
		Promise.then (async)	
		(anonymous)					@ renderer.js:2
		Promise.then (async)	
		mounted						@ renderer.js:2
		Si						@ renderer.js:2
		gn						@ renderer.js:2
		insert						@ renderer.js:2
		x						@ renderer.js:2
		Qa.nodeOps					@ renderer.js:2
		t._update					@ renderer.js:2
		n						@ renderer.js:2
		t.get						@ renderer.js:2
		t						@ renderer.js:2
		t						@ renderer.js:2
		os.$mount					@ renderer.js:2
		t._init						@ renderer.js:2
		os						@ renderer.js:2
		(anonymous)					@ renderer.js:2
		(anonymous)					@ renderer.js:2
		(anonymous)					@ renderer.js:2
```

It then either stays empty, if fallback to Invidious is disabled, or falls back to Invidious, as expected.

### Expected Behavior

Regular playback.

### Issue Labels

API issue

### FreeTube Version

v.0.21.0 Beta, also present on most recent nightly, v0.21.0-nightly-4555

### Operating System Version

Windows 10 version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.0, but about 8 hours ago

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by UnconsciousBlaringHuman** [comment]
Took too long writing the issue, and didn't recheck before opening it, my apologies.
Duplicate of #5378
